### ISSUE TITLE
Python version check

### ISSUE THREAD

**Issue by ErwinKomen** [ErwinKomen/RU-MultiL#38]
AWS says that support for Python 3.9 will increasingly decline.
TODO:
1. Check which Python version we are using in the Lambda's
2. Update the version, if possible without problem(s)

**Comment by ErwinKomen** [comment]
### Observations
1. We have a file `template.yaml` inside the `labdas` folder, and this one has python information
    1. It provides the current python version for each function, which is `python3.9`
    1. For example: see below for part of the template
1. Surely the python version specified here depends on the python version supplied by the AWS in the system we use as base
    1. So where is that system specified?

```
Resources:
  MultiLappList:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: multil_list/
      Handler: labda_list.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        MultiLapp:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /list
            Method: get
```

### Online
1. Signed into aws.amazon.com/console
2. Overview is in [Lambda > functions](https://eu-central-1.console.aws.amazon.com/lambda/home?region=eu-central-1#/functions)
